spring.application.name=carro-service
server.port=8082

#--- spring lanza una excepcion si no se encuentra un handler  ---#
spring.mvc.throw-exception-if-no-handler-found=true

#---
# spring boot registra automaticamente los mapeos para servir archivos estaticos (imagenes, css, js)
# desde /static, /public, /resources,

# con false se desactivan los mapeos automaticos, si no existe un endpoint lanzara una excepcion.
# ---#
spring.web.resources.add-mappings=false