server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: carro-service
  mvc:
    #--- spring lanza una excepcion si no se encuentra un handler  ---#
    throw-exception-if-no-handler-found: true 
  web:
    resources:
    #---
    # spring boot registra automaticamente los mapeos para servir archivos estaticos (imagenes, css, js)
    # desde /static, /public, /resources,

    # con false se desactivan los mapeos automaticos, si no existe un endpoint lanzara una excepcion.
    # ---#
      add-mappings: false
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      default-zone: http://localhost:8761/eureka
    instance: 
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


